Hotel Tre Monti/Controllers/PrenotazioniController.cs
using Hotel_Tre_Monti.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Hotel_Tre_Monti.Controllers
{
    public class PrenotazioniController : Controller
    {
        // GET: Prenotazioni
        private string connectionString = System.Configuration.ConfigurationManager.ConnectionStrings["gestionale"].ConnectionString;
        public ActionResult Index()
        {
            List<Prenotazione> prenotazioni = new List<Prenotazione>();

            try
            {
                using (SqlConnection conn = new SqlConnection(connectionString))
                {
                    conn.Open();

                    string sql = "SELECT * FROM Prenotazioni";
                    SqlCommand cmd = new SqlCommand(sql, conn);

                    SqlDataReader reader = cmd.ExecuteReader();

                    while (reader.Read())
                    {
                        Prenotazione prenotazione = new Prenotazione
                        {
                            NumeroPrenotazione = (int)reader["NumeroPrenotazione"],
                            CodiceFiscaleCliente = reader["CodiceFiscaleCliente"].ToString(),
                            NumeroCamera = (int)reader["NumeroCamera"],
                            DataPrenotazione = (DateTime)reader["DataPrenotazione"],
                            NumeroProgressivoAnno = (int)reader["NumeroProgressivoAnno"],
                            Anno = (int)reader["Anno"],
                            PeriodoDal = (DateTime)reader["PeriodoDal"],
                            PeriodoAl = (DateTime)reader["PeriodoAl"],
                            CaparraConfirmatoria = (decimal)reader["CaparraConfirmatoria"],
                            Tariffa = (decimal)reader["Tariffa"],
                            MezzaPensione = (bool)reader["MezzaPensione"],
                            PensioneCompleta = (bool)reader["PensioneCompleta"],
                            PernottamentoConColazione = (bool)reader["PernottamentoConColazione"]
                        };

                        prenotazioni.Add(prenotazione);
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);

            }

            return View(prenotazioni);
        }


        public ActionResult VisualizzaCamere()
        {
            List<Camera> camereDisponibili = GetCamereDisponibili();

            ViewBag.Tariffe = GetTariffe();

            return View(camereDisponibili);
        }

        public ActionResult ConfermaPrenotazione()
        {

            return View();
        }

        public ActionResult Prenota()
        {

            return View();
        }

        [HttpPost]
        public ActionResult Prenota(string codiceFiscaleCliente, int numeroCamera, DateTime? dataPrenotazione, int numeroProgressivoAnno, int anno, DateTime? periodoDal, DateTime? periodoAl, decimal caparraConfirmatoria, decimal tariffa, bool? mezzaPensione, bool? pensioneCompleta, bool? colazione)
        {
            // Esegui la logica di gestione della prenotazione
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();

                // Esempio: Inserisci i dati della prenotazione nel database
                string query = "INSERT INTO Prenotazioni ( CodiceFiscaleCliente, NumeroCamera, DataPrenotazione, NumeroProgressivoAnno, Anno, PeriodoDal, PeriodoAl, CaparraConfirmatoria, Tariffa, MezzaPensione, PensioneCompleta, PernottamentoConColazione) " +
                               "VALUES (@CodiceFiscaleCliente, @NumeroCamera, @DataPrenotazione,@NumeroProgressivoAnno, @Anno, @PeriodoDal, @PeriodoAl, @CaparraConfirmatoria, @Tariffa, @MezzaPensione, @PensioneCompleta, @PernottamentoConColazione)";

                using (SqlCommand command = new SqlCommand(query, connection))
                {
                    command.Parameters.AddWithValue("@CodiceFiscaleCliente", codiceFiscaleCliente);
                    command.Parameters.AddWithValue("@NumeroCamera", numeroCamera);
                    command.Parameters.AddWithValue("@DataPrenotazione", dataPrenotazione);
                    command.Parameters.AddWithValue("@NumeroProgressivoAnno", numeroProgressivoAnno);
                    command.Parameters.AddWithValue("@Anno", (int)anno);
                    command.Parameters.AddWithValue("@PeriodoDal", (object)periodoDal ?? DBNull.Value);
                    command.Parameters.AddWithValue("@PeriodoAl", (object)periodoAl ?? DBNull.Value);
                    command.Parameters.AddWithValue("@CaparraConfirmatoria", caparraConfirmatoria);
                    command.Parameters.AddWithValue("@Tariffa", tariffa);
                    command.Parameters.AddWithValue("@MezzaPensione", (object)mezzaPensione ?? DBNull.Value);
                    command.Parameters.AddWithValue("@PensioneCompleta", (object)pensioneCompleta ?? DBNull.Value);
                    command.Parameters.AddWithValue("@PernottamentoConColazione", (object)colazione ?? DBNull.Value);

                    command.ExecuteNonQuery();
                }
            }

            // Reindirizza a una pagina di conferma o altro
            return RedirectToAction("ConfermaPrenotazione");
        }

        private List<Camera> GetCamereDisponibili()
        {
            List<Camera> camereDisponibili = new List<Camera>();

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();

                // Esempio: Recupera le camere disponibili dal database
                string query = "SELECT * FROM Camere";

                using (SqlCommand command = new SqlCommand(query, connection))
                {
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            Camera camera = new Camera
                            {
                                Numero = Convert.ToInt32(reader["Numero"]),
                                Descrizione = reader["Descrizione"].ToString(),
                                Tipologia = reader["Tipologia"].ToString()
                            };

                            camereDisponibili.Add(camera);
                        }
                    }
                }
            }

            return camereDisponibili;
        }

        private List<decimal> GetTariffe()
        {
            List<decimal> tariffe = new List<decimal>();

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();

                // Esempio: Recupera le tariffe dalla tabella Prenotazioni
                string query = "SELECT DISTINCT Tariffa FROM Prenotazioni";

                using (SqlCommand command = new SqlCommand(query, connection))
                {
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            decimal tariffa = Convert.ToDecimal(reader["Tariffa"]);
                            tariffe.Add(tariffa);
                        }
                    }
                }
            }

            return tariffe;
        }

        public ActionResult Details(int numeroPrenotazione)
        {
            Prenotazione prenotazione = null;

            using (SqlConnection conn = new SqlConnection(connectionString))
            {

                string sql = "SELECT * FROM Prenotazioni WHERE NumeroPrenotazione = @NumeroPrenotazione";
                SqlCommand cmd = new SqlCommand(sql, conn);
                cmd.Parameters.AddWithValue("@NumeroPrenotazione", numeroPrenotazione);

                try
                {
                    conn.Open();
                    SqlDataReader reader = cmd.ExecuteReader();


                    if (reader.Read())
                    {
                        prenotazione = new Prenotazione
                        {
                            NumeroPrenotazione = (int)reader["NumeroPrenotazione"],
                            CodiceFiscaleCliente = reader["CodiceFiscaleCliente"].ToString(),
                            NumeroCamera = (int)reader["NumeroCamera"],
                            DataPrenotazione = (DateTime)reader["DataPrenotazione"],
                            NumeroProgressivoAnno = (int)reader["NumeroProgressivoAnno"],
                            Anno = (int)reader["Anno"],
                            PeriodoDal = (DateTime)reader["PeriodoDal"],
                            PeriodoAl = (DateTime)reader["PeriodoAl"],
                            CaparraConfirmatoria = (decimal)reader["CaparraConfirmatoria"],
                            Tariffa = (decimal)reader["Tariffa"],
                            MezzaPensione = (bool)reader["MezzaPensione"],
                            PensioneCompleta = (bool)reader["PensioneCompleta"],
                            PernottamentoConColazione = (bool)reader["PernottamentoConColazione"]
                        };
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);

                }
            }

            if (prenotazione == null)
            {
                return RedirectToAction("Index");
            }


            return View(prenotazione);
        }

        public ActionResult Checkout(int numeroPrenotazione)
        {
            Prenotazione prenotazione = null;

            using (SqlConnection conn = new SqlConnection(connectionString))
            {

                string sql = "SELECT * FROM Prenotazioni WHERE NumeroPrenotazione = @NumeroPrenotazione";

Hotel Tre Monti/Views/Prenotazioni/AggiungiServizio.cshtml
@model Hotel_Tre_Monti.Models.ServizioAggiuntivo

@{
    ViewBag.Title = "AggiungiServizio";
}

<h2>AggiungiServizio</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>ServizioAggiuntivo</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
    @Html.LabelFor(model => model.NumeroPrenotazione, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.NumeroPrenotazione, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.NumeroPrenotazione, "", new { @class = "text-danger" })
    </div>
</div>
        <div class="form-group">
            @Html.LabelFor(model => model.DataServizio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataServizio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataServizio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoServizio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TipoServizio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TipoServizio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantita, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantita, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantita, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prezzo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prezzo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prezzo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Hotel Tre Monti/Views/Prenotazioni/Checkout.cshtml
@model Hotel_Tre_Monti.Models.Prenotazione

<h2>Checkout</h2>

<p>Numero Stanza: @Model.NumeroCamera</p>
<p>Periodo: @Model.PeriodoDal.ToString("dd/MM/yyyy") - @Model.PeriodoAl.ToString("dd/MM/yyyy")</p>
<p>Tariffa Applicata: @Model.Tariffa</p>


<button onclick="window.print()">Stampa Dettaglio Prenotazione</button>

Hotel Tre Monti/Views/Prenotazioni/ConfermaPrenotazione.cshtml
@{
    ViewBag.Title = "ConfermaPrenotazione";
}

<h2>Prenotazione effettuata con successo</h2>

Hotel Tre Monti/Views/Prenotazioni/Details.cshtml
@model Hotel_Tre_Monti.Models.Prenotazione

@{
    ViewBag.Title = "Dettaglio Prenotazione";
}

<h2>Dettaglio Prenotazione</h2>

<p>
    @Html.ActionLink("Torna alla Lista", "Index")
</p>

<!-- Mostra dettagli prenotazione -->
<div>
    <h4>Dettagli Prenotazione</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NumeroPrenotazione)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NumeroPrenotazione)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CodiceFiscaleCliente)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CodiceFiscaleCliente)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumeroCamera)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NumeroCamera)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataPrenotazione)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DataPrenotazione)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumeroProgressivoAnno)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NumeroProgressivoAnno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Anno)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Anno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PeriodoDal)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PeriodoDal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PeriodoAl)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PeriodoAl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CaparraConfirmatoria)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CaparraConfirmatoria)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tariffa)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Tariffa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MezzaPensione)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MezzaPensione)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PensioneCompleta)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PensioneCompleta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PernottamentoConColazione)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PernottamentoConColazione)
        </dd>

        <!-- Aggiungi altre proprietà della prenotazione -->
        <!-- Mostra servizi aggiuntivi -->
        <dt>Servizi Aggiuntivi</dt>
        <dd>
            <ul>
                @foreach (var servizio in Model.ServiziAggiuntivi)
                {
                    <li>@servizio.TipoServizio - Quantità: @servizio.Quantita, Prezzo: @servizio.Prezzo</li>
                }
            </ul>
        </dd>
    </dl>
</div>

Hotel Tre Monti/Views/Prenotazioni/Index.cshtml
@model IEnumerable<Hotel_Tre_Monti.Models.Prenotazione>

@{
    ViewBag.Title = "Lista Prenotazioni";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Prenota")
</p>
<div class="container table-responsive">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NumeroPrenotazione)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CodiceFiscaleCliente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumeroCamera)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataPrenotazione)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumeroProgressivoAnno)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Anno)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PeriodoDal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PeriodoAl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CaparraConfirmatoria)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tariffa)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MezzaPensione)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PensioneCompleta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PernottamentoConColazione)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NumeroPrenotazione)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CodiceFiscaleCliente)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumeroCamera)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataPrenotazione)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumeroProgressivoAnno)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Anno)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PeriodoDal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PeriodoAl)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CaparraConfirmatoria)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tariffa)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MezzaPensione)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PensioneCompleta)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PernottamentoConColazione)
                </td>
                <td>
                    
                    @Html.ActionLink("Details", "Details", new { numeroPrenotazione = item.NumeroPrenotazione })
                    @Html.ActionLink("Effettua Checkout", "Checkout", new { numeroPrenotazione = item.NumeroPrenotazione })
                    
                </td>
            </tr>
        }

    </table>
</div>

Hotel Tre Monti/Views/Prenotazioni/Prenota.cshtml
@model Hotel_Tre_Monti.Models.Prenotazione

@{
    ViewBag.Title = "Prenota";
}

<h2>Prenota</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Prenotazione</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CodiceFiscaleCliente, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CodiceFiscaleCliente, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CodiceFiscaleCliente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumeroCamera, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumeroCamera, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumeroCamera, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataPrenotazione, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataPrenotazione, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataPrenotazione, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumeroProgressivoAnno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumeroProgressivoAnno, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumeroProgressivoAnno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Anno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Anno, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Anno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PeriodoDal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PeriodoDal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PeriodoDal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PeriodoAl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PeriodoAl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PeriodoAl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CaparraConfirmatoria, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CaparraConfirmatoria, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CaparraConfirmatoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tariffa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tariffa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tariffa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MezzaPensione, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.MezzaPensione)
                    @Html.ValidationMessageFor(model => model.MezzaPensione, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PensioneCompleta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.PensioneCompleta)
                    @Html.ValidationMessageFor(model => model.PensioneCompleta, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PernottamentoConColazione, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.PernottamentoConColazione)
                    @Html.ValidationMessageFor(model => model.PernottamentoConColazione, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Hotel Tre Monti/Views/Prenotazioni/VisualizzaCamere.cshtml
@model IEnumerable<Hotel_Tre_Monti.Models.Camera>

@{
    ViewBag.Title = "VisualizzaCamere";
}

<h2>VisualizzaCamere</h2>

<p>
    @Html.ActionLink("Prenota Camera", "Prenota", "Prenotazioni", new { area = "" }, new { @class = "btn btn-primary" })
</p>

@Html.ActionLink("Servizi Aggiuntivi", "AggiungiServizio", "Prenotazioni", new { area = "" }, new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Descrizione)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tipologia)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Descrizione)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tipologia)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Numero }) |
                @Html.ActionLink("Details", "Details", new { id = item.Numero }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Numero })
            </td>
        </tr>
    }

</table>